'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,ChevronRight,Crown,MessageCircle,Send,Sparkles,Target,TrendingUp,Users} from 'lucide-react';

const suggestions=['Cliente disse “está caro”. O que respondo?','Crie uma promoção para preencher a agenda amanhã','Escreva uma mensagem para clientes que sumiram'];
function dayKey(){return new Date().toLocaleDateString('en-CA')}

export default function Home(){
 const [input,setInput]=useState('');const [messages,setMessages]=useState([{role:'ai',text:'Olá! Cole aqui a conversa do seu cliente ou conte o que você precisa. Eu preparo uma resposta profissional para você enviar.'}]);const [used,setUsed]=useState(0);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const box=useRef(null);
 useEffect(()=>{const saved=JSON.parse(localStorage.getItem('ontop-free-usage')||'{}');if(saved.day===dayKey())setUsed(saved.count||0)},[]);
 useEffect(()=>{box.current?.scrollTo({top:box.current.scrollHeight,behavior:'smooth'})},[messages]);
 async function send(value=input){const text=value.trim();if(text.length<2||busy){if(text.length>0&&text.length<2)setNotice('Escreva pelo menos 2 caracteres.');return}if(used>=5){setNotice('Você usou as 5 respostas de hoje. Seu limite renova amanhã.');return}setMessages(m=>[...m,{role:'user',text}]);setInput('');setBusy(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});const d=await r.json().catch(()=>({error:'Resposta inválida do servidor.'}));if(!r.ok){setNotice(d.error);if(typeof d.remaining==='number')setUsed(5-d.remaining);return}setUsed(5-d.remaining);localStorage.setItem('ontop-free-usage',JSON.stringify({day:dayKey(),count:5-d.remaining}));setMessages(m=>[...m,{role:'ai',text:d.answer}])}catch{setNotice('Não foi possível conectar agora. Verifique sua internet e tente novamente.')}finally{setBusy(false)}}
 async function premium(){const url=process.env.NEXT_PUBLIC_KIWIFY_CHECKOUT_URL;await fetch('/api/track',{method:'POST'}).catch(()=>{});if(url)location.href=url;else setNotice('O checkout seguro será liberado em breve.')}
 return <main>
  <nav><a className="brand" href="#top"><span>O</span><b>OnTop</b><em>Atendimento IA</em></a><button className="navCta" onClick={premium}>Conhecer Premium <ArrowRight size={16}/></button></nav>
  <section className="hero" id="top"><div className="eyebrow"><Sparkles size={15}/> Assistente para profissionais de beleza</div><h1>Não perca clientes por<br/><span>não saber o que responder.</span></h1><p>Cole a conversa do WhatsApp e receba uma resposta profissional para tentar transformar interesse em agendamento.</p><div className="trust"><span><Check/> Sem cartão</span><span><Check/> 5 respostas por dia</span><span><Check/> Renova diariamente</span></div></section>
  <section className="workspace"><div className="chatHead"><div className="avatar"><Sparkles/></div><div><strong>Assistente OnTop</strong><small><i/> {busy?'preparando resposta':'online agora'}</small></div><div className="meter"><b>{5-used}</b><span>respostas hoje</span></div></div><div className="messages" ref={box}>{messages.map((m,i)=><div key={i} className={'msg '+m.role}>{m.text}</div>)}</div><div className="chips">{suggestions.map(s=><button key={s} disabled={busy} onClick={()=>send(s)}>{s}<ChevronRight size={14}/></button>)}</div><div className="composer"><textarea aria-label="Mensagem" value={input} disabled={busy} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Cole a conversa ou escreva sua dúvida..."/><button disabled={busy||input.trim().length<2} onClick={()=>send()} aria-label="Enviar"><Send/></button></div><small className="enter">Mínimo de 2 caracteres • Enter para enviar</small></section>
  <section className="benefits"><article><MessageCircle/><h3>Resposta certa</h3><p>Responda dúvidas e objeções com clareza, educação e foco no agendamento.</p></article><article><Target/><h3>Promoções prontas</h3><p>Crie ofertas para datas e horários específicos sem parecer mensagem genérica.</p></article><article><Users/><h3>Clientes de volta</h3><p>Recupere contatos parados com mensagens naturais e personalizadas.</p></article></section>
  <section className="premium"><div className="premiumCopy"><div className="eyebrow gold"><Crown size={15}/> OnTop Premium</div><h2>Mais respostas.<br/>Mais oportunidades.</h2><p>Tenha 50 respostas renovadas todos os dias para atender, divulgar e acompanhar seus clientes.</p><ul><li><Check/>50 respostas por dia</li><li><Check/>Respostas mais completas</li><li><Check/>Análise de conversas</li><li><Check/>Promoções e recuperação de clientes</li></ul></div><div className="priceCard"><span>Plano de lançamento</span><div className="price"><small>R$</small>11<sup>,90</sup><em>/mês</em></div><p>Cancele quando quiser.</p><button onClick={premium}>OBTER O PREMIUM <ArrowRight/></button><small>Compra processada com segurança pela Kiwify</small></div></section>
  {notice&&<div className="toast" onClick={()=>setNotice('')}>{notice}</div>}
  <footer><div className="brand"><span>O</span><b>OnTop</b></div><p>Atendimento inteligente para quem vive do próprio negócio.</p></footer>
 </main>
}
